export default [
  {
    id: 1,
    obesitas: 'Tidak',
    hdk: 'Tidak',
    ppp: 'Tidak',
    infeksi: 'Ya',
    lain_lain: '-',
  },
  {
    id: 2,
    obesitas: 'Tidak',
    hdk: 'Ya',
    ppp: 'Tidak',
    infeksi: 'Tidak',
    lain_lain: '-',
  },
  {
    id: 3,
    obesitas: 'Tidak',
    hdk: 'Tidak',
    ppp: 'Ya',
    infeksi: 'Ya',
    lain_lain: '-',
  },
  {
    id: 4,
    obesitas: 'Ya',
    hdk: 'Tidak',
    ppp: 'Tidak',
    infeksi: 'Tidak',
    lain_lain: '-',
  },
  {
    id: 5,
    obesitas: 'Tidak',
    hdk: 'Tidak',
    ppp: 'Ya',
    infeksi: 'Tidak',
    lain_lain: '-',
  },
];
