export default [
  {
    id: 1,
    usia_kehamilan: '34',
    hpht: '2024-05-15',
    taksiran_persalinan: '2025-02-19',
    presentasi: 'BK',
    cara_persalinan: 'Normal',
    tempat: 'RS',
    alamat: 'Cirebon',
    penolong: 'Dokter Umum',
  },
  {
    id: 2,
    usia_kehamilan: '18',
    hpht: '2024-09-14',
    taksiran_persalinan: '2025-06-22',
    presentasi: 'KK',
    cara_persalinan: 'Normal',
    tempat: 'RB',
    alamat: 'Cirebon',
    penolong: 'Dokter Spesialis',
  },
  {
    id: 3,
    usia_kehamilan: '14',
    hpht: '2024-10-12',
    taksiran_persalinan: '2025-07-19',
    presentasi: 'DH',
    cara_persalinan: 'Tindakan',
    tempat: 'RSIA',
    alamat: 'Cirebon',
    penolong: 'Dokter Umum',
  },
  {
    id: 4,
    usia_kehamilan: '26',
    hpht: '2024-07-20',
    taksiran_persalinan: '2025-04-26',
    presentasi: 'LLO',
    cara_persalinan: 'Normal',
    tempat: 'Rumah',
    alamat: 'Cirebon',
    penolong: 'Bidan',
  },
  {
    id: 5,
    usia_kehamilan: '17',
    hpht: '2024-10-19',
    taksiran_persalinan: '2025-08-05',
    presentasi: 'BG',
    cara_persalinan: 'Normal',
    tempat: 'Puskesmas',
    alamat: 'Cirebon',
    penolong: 'Bidan',
  },
];
